name: My CI Build + Test

on: 
  push: 
    branches: 
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Build step
            run:  echo "Building application..."

  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test - Check if index.html exists
        run: |
          if [ -f index.html ]; then
            echo "File exists"
          else
            echo "File not exists"  
            exit 1
          fi 